name: Build and Configure OpenWrt

on:
  workflow_dispatch:
    inputs:
      enable-ssh:
        description: "Enable SSH connection"
        required: false
        default: "false"

jobs:
  build:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout OpenWrt Repository
        uses: actions/checkout@v2

    

      - name: Enable SSH
        if: ${{ github.event.inputs.enable-ssh == 'true' }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Connect via SSH and Configure
        if: ${{ github.event.inputs.enable-ssh == 'true' }}
        run: |
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" user@your-openwrt-device "cd /path/to/your/openwrt && make menuconfig"

    

      # ... (其他步骤，如上传固件等)

