name: Copy OpenWrt Config

on:
  workflow_dispatch:
    inputs:
      enable-ssh:
        description: "Enable SSH connection"
        required: false
        default: "false"

jobs:
  copy_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt Repository
        uses: actions/checkout@v2

      

      - name: Enable SSH
        if: ${{ github.event.inputs.enable-ssh == 'true' }}
        run: echo "SSH is enabled"

      - name: Print Enable SSH
        if: ${{ github.event.inputs.enable-ssh == 'true' }}
        run: echo "SSH is enabled, you can add your SSH commands here"
