name: Build and Configure OpenWrt

on:
  workflow_dispatch:
    inputs:
      enable-ssh:
        description: "Enable SSH connection"
        required: false
        default: "false"

jobs:
  build_and_configure:
    name: Build and Configure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt Repository
        uses: actions/checkout@v2

     

      - name: Clone OpenWrt Repository
        run: git clone https://github.com/coolsnowwolf/lede

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: Generate .config
        run: |
          cd lede
          cp /home/runner/work/R3G/R3G/quan.config .config
          make defconfig

      

      - name: SSH connection to Actions
        uses: appleboy/ssh-action@master
        if: ${{ github.event.inputs.enable-ssh == 'true' }}
        with:
          host: your-openwrt-device
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add your SSH commands here
